### ISSUE TITLE
How to run the demo

### ISSUE THREAD

**Issue by diego1199** [cyrixmorten/parse-angular-crud-demo#2]
Hi, i'm recently starting on Node.js so i wasn't able to run the demo."

I've downloaded the project, change the application keys, and type:

> node web-server.js

But when i'm entering on localhost:8000 i'am only getting the directory list and when i try with localhost:800/app/index.html i'm getting 404 not found.

Please can you help me to run the demo.

Thanks

**Comment by cyrixmorten** [comment]
Hi @diego1199 

Thanks for trying out this library but unfortunately it has not been maintained for a long time.

Since the last update parse.com has been open sourced which means all the parse.com dependencies needs to be updated.
